### ISSUE TITLE
追踪是否需要改进一下

### ISSUE THREAD

**Issue by Littleboyss** [rpcxio/rpcx-plugins#2]
![image](https://github.com/rpcxio/rpcx-plugins/assets/23073704/dc44bece-4186-4f2d-a71c-355e198f05d4)
event请求和返回的参数都没有
![image](https://github.com/rpcxio/rpcx-plugins/assets/23073704/25b072a5-5ab4-4253-aba1-d703480af843)
我为这个追踪增加了payload和metadata参数记录 ,Header记录时是二进制且没有官方转string的方法目前没有记录

**Comment by Littleboyss** [comment]
稍等我会提交一个pr,您看下需不需要修改下

**Comment by smallnest** [comment]
欢迎提交PR
